name: Build Pico2 Firmware

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ARM GCC Toolchain + Build Dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build gcc-arm-none-eabi libnewlib-arm-none-eabi

      - name: Clone Pico-SDK (RP2350 support)
        run: |
          git clone --depth=1 --branch master https://github.com/raspberrypi/pico-sdk.git
          git -C pico-sdk submodule update --init
        env:
          PICO_SDK_PATH: ${{ github.workspace }}/pico-sdk

      - name: Configure build
        run: |
          mkdir -p build
          cd build
          cmake .. -DPICO_BOARD=pico2 -G Ninja
        env:
          PICO_SDK_PATH: ${{ github.workspace }}/pico-sdk

      - name: Build Firmware
        run: |
          cd build
          ninja -v
